# Generated by Django 4.0.2 on 2022-02-19 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_description', models.TextField()),
                ('category_img', models.ImageField(default='cat.svg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=150)),
                ('pro_description', models.TextField()),
                ('pro_img', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('pro_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('pro_category', models.ManyToManyField(to='main.Category')),
            ],
        ),
    ]
