# Generated by Django 4.0.2 on 2022-02-23 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demamde_sujet', models.CharField(max_length=100, null=True)),
                ('demamde_description', models.TextField(null=True)),
                ('demande_modification', models.DateField(auto_now=True, null=True)),
                ('demande_creation', models.DateField(auto_now_add=True, null=True)),
                ('demamde_utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
