# Generated by Django 4.0.2 on 2022-02-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_category_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande_client',
            old_name='demamde_description',
            new_name='demande_description',
        ),
        migrations.RenameField(
            model_name='demande_client',
            old_name='demamde_sujet',
            new_name='demande_sujet',
        ),
        migrations.RenameField(
            model_name='demande_client',
            old_name='demamde_utilisateur',
            new_name='demande_utilisateur',
        ),
    ]
