# Generated by Django 3.2.7 on 2022-02-23 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_userprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='user_adresse',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='user_nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='user_prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='user_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='user_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='user_profil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='user_tel',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
