# Generated by Django 3.2.7 on 2022-02-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220223_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofil',
            options={'managed': False},
        ),
    ]
