# Generated by Django 3.2.7 on 2022-02-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofil',
            options={},
        ),
    ]
