# Generated by Django 3.2.7 on 2022-02-24 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_userprofil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_client',
            name='demande_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='demande_client',
            name='demande_datevoulue',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='user_profil',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
