# Generated by Django 3.2.7 on 2022-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220224_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='user_isPro',
            field=models.BooleanField(default=False),
        ),
    ]
