# Generated by Django 4.0.4 on 2022-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofil_user_ispro'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_client',
            name='demande_onGoing',
            field=models.BooleanField(blank=True, default='True', null=True),
        ),
    ]
